// Backup question bank, used when no ANTHROPIC_API_KEY is set or the AI call fails.
export const QUESTION_BANK = [
  "Who in the group is the most self-obsessed?",
  "Who is most likely to become famous one day?",
  "Who takes the longest to reply to messages?",
  "Who is most likely to be late to their own wedding?",
  "Who would survive the longest in a zombie apocalypse?",
  "Who is the biggest foodie in the group?",
  "Who is most likely to cry during a movie?",
  "Who spends the most time on their phone?",
  "Who is the best at keeping secrets?",
  "Who is the worst at keeping secrets?",
  "Who is most likely to forget a friend's birthday?",
  "Who would be the best stand-up comedian?",
  "Who is the most competitive person here?",
  "Who is most likely to fall asleep at a party?",
  "Who gives the best advice?",
  "Who is most likely to go viral on social media?",
  "Who is the biggest drama queen or king?",
  "Who is most likely to start a business?",
  "Who would win a dance-off?",
  "Who has the most chaotic camera roll?",
  "Who is most likely to get lost even with Google Maps?",
  "Who is the most likely to adopt ten pets?",
  "Who is the group's unofficial therapist?",
  "Who takes the most selfies?",
  "Who is most likely to say 'I'm 5 minutes away' while still at home?",
  "Who would be the first to quit a reality show?",
  "Who would win a reality show?",
  "Who is the pickiest eater?",
  "Who is most likely to laugh at the wrong moment?",
  "Who is the best cook?",
  "Who is most likely to spend all their salary in one day?",
  "Who is the most organised person in the group?",
  "Who has the best fashion sense?",
  "Who is most likely to become a motivational speaker?",
  "Who is most likely to argue with a referee?",
  "Who is the loudest person in the group?",
  "Who is the best at giving gifts?",
  "Who is most likely to binge an entire series in one night?",
  "Who is most likely to be caught talking to themselves?",
  "Who would make the best teacher?",
  "Who is most likely to move to another country on a whim?",
  "Who is the biggest overthinker?",
  "Who would be the worst at keeping a plant alive?",
  "Who is most likely to send a message to the wrong group chat?",
  "Who is the best storyteller?",
  "Who exaggerates their stories the most?",
  "Who is most likely to win a quiz night?",
  "Who is most likely to cancel plans last minute?",
  "Who is the most adventurous eater?",
  "Who would be the best travel buddy?",
  "Who is most likely to get a tattoo on impulse?",
  "Who is most likely to become a politician?",
  "Who would make the best detective?",
  "Who is the most stubborn?",
  "Who has the most contagious laugh?",
  "Who is most likely to be found at the snack table?",
  "Who is the biggest gym enthusiast?",
  "Who is most likely to sleep through an alarm?",
  "Who is the best at bargaining while shopping?",
  "Who is most likely to try every new trend?",
  "Who is most likely to forget where they parked?",
  "Who would be the best wedding planner?",
  "Who is the most likely to secretly be a superhero?",
  "Who is the calmest in a crisis?",
  "Who panics the most in a crisis?",
  "Who is the biggest gossip?",
  "Who would be the first to volunteer for anything?",
  "Who is most likely to write a book?",
  "Who is most likely to sing in the shower the loudest?",
  "Who is most likely to win the lottery and lose the ticket?",
  "Who is the best at remembering names?",
  "Who is the worst at remembering names?",
  "Who is most likely to break something expensive?",
  "Who would be the best captain of a sports team?",
  "Who is the most likely to start a group chat argument?",
  "Who is the most patient person here?",
  "Who is most likely to have a secret talent?",
  "Who is the biggest night owl?",
  "Who is the earliest riser?",
  "Who is most likely to eat someone else's lunch from the fridge?",
  "Who is the most likely to become a millionaire?",
  "Who would be the best at escaping an escape room?",
  "Who is most likely to cry at a wedding?",
  "Who is most likely to fall for a prank?",
  "Who is the best prankster?",
  "Who is most likely to be mistaken for a celebrity?",
  "Who has the most interesting playlist?",
  "Who is most likely to take charge when plans fall apart?",
  "Who is the most likely to overpack for a weekend trip?",
  "Who is most likely to reply 'ok' to a long message?",
  "Who would be the best host for a party?",
  "Who is the most likely to get into a debate about movies?",
  "Who is most likely to know all the latest memes?",
  "Who would be the best at haggling with an auto driver?",
  "Who is most likely to get distracted mid-sentence?",
  "Who is the most generous person in the group?",
  "Who is most likely to adopt a weird hobby?",
  "Who is most likely to survive alone on an island?",
  "Who would be the worst roommate?",
  "Who would be the best roommate?",
  "Who is the group's biggest optimist?",
  "Who is most likely to become a YouTuber?",
  "Who is most likely to win an argument without being right?",
  "Who has the best poker face?",
  "Who is most likely to cheat at board games?",
  "Who is most likely to be the last one to leave a party?",
  "Who is the best at taking photos of others?",
  "Who is the most likely to remember every inside joke?",
  "Who is most likely to fall asleep during a meeting?",
  "Who is the group's tech support?",
  "Who is most likely to order the same dish every time?",
  "Who would be the best at running a café?",
  "Who is the most likely to become a meme?",
  "Who would be the best partner in a crime movie heist?",
  "Who is most likely to forget their own password?",
  "Who is the biggest cricket fan?",
  "Who is the most likely to start singing at random?",
  "Who is most likely to plan the next group trip?",
  "Who is the most likely to say 'trust me' right before a disaster?"
];

export function pickFromBank(count, used) {
  const usedSet = new Set(used.map((q) => q.toLowerCase()));
  let pool = QUESTION_BANK.filter((q) => !usedSet.has(q.toLowerCase()));
  // Every question has been played in this room; start the cycle again.
  if (pool.length < count) pool = [...QUESTION_BANK];
  for (let i = pool.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [pool[i], pool[j]] = [pool[j], pool[i]];
  }
  return pool.slice(0, count);
}
